<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="EPINBANW03CF" failures="1" tests="2" name="Test" time="0.044" errors="0" timestamp="2022-05-09T15:41:03 IST">
  <testcase classname="com.calculator.Testcases" name="testpass" time="0.012"/>
  <testcase classname="com.calculator.Testcases" name="testfail" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [10.0] but found [30.0]">
      <![CDATA[java.lang.AssertionError: expected [10.0] but found [30.0]
at com.calculator.Testcases.testfail(Testcases.java:27)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testfail -->
  <testcase classname="com.calculator.Testcases" name="paramdata" time="0.0">
    <ignored/>
  </testcase> <!-- paramdata -->
  <testcase classname="com.calculator.Testcases" name="testfail2" time="0.0">
    <ignored/>
  </testcase> <!-- testfail2 -->
  <testcase classname="com.calculator.Testcases" name="testDivByZero" time="0.0">
    <ignored/>
  </testcase> <!-- testDivByZero -->
  <testcase classname="com.calculator.Testcases" name="testfail1" time="0.0">
    <ignored/>
  </testcase> <!-- testfail1 -->
  <testcase classname="com.calculator.Testcases" name="testpass2" time="0.0">
    <ignored/>
  </testcase> <!-- testpass2 -->
  <testcase classname="com.calculator.Testcases" name="testpass1" time="0.0">
    <ignored/>
  </testcase> <!-- testpass1 -->
</testsuite> <!-- Test -->
